spring:
  datasource:
    url: jdbc:postgresql://roundhouse.proxy.rlwy.net:53232/railway
    username: postgres
    password: 3A*gf3d6gaBeAE5G-b56652fEFc*E-g5
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

